version: "3"

services:
  saleor-app-checkout:
    container_name: saleor-app-checkout
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        - SALEOR_API_URL=http://localhost:8000/graphql/ # handled by nginx
        - STOREFRONT_URL=http://localhost:3000
        - CHECKOUT_APP_URL=http://localhost:3001
        - CHECKOUT_STOREFRONT_URL=http://localhost:3001/checkout-spa/
        - CLOUD_DEPLOYMENT_URL=
    ports:
      - 3001:3001
    command: pnpm turbo run start --filter=saleor-app-checkout...
  storefront:
    container_name: storefront
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        - SALEOR_API_URL=http://localhost:8000/graphql/ # handled by nginx
        - STOREFRONT_URL=http://localhost:3000
        - CHECKOUT_APP_URL=http://localhost:3001
        - CHECKOUT_STOREFRONT_URL=http://localhost:3001/checkout-spa/
        - CLOUD_DEPLOYMENT_URL=
    ports:
      - 3000:3000
    command: sh -c '(nginx &) && pnpm turbo run start --filter=storefront...'
