version: "3"

services:
  saleor-storefront:
    container_name: saleor-storefront
    build:
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SALEOR_API_URL: ${NEXT_PUBLIC_SALEOR_API_URL}
        NEXT_PUBLIC_STOREFRONT_URL: ${NEXT_PUBLIC_STOREFRONT_URL}
    restart: always
    ports:
      - 3001:3001
    networks:
      - dokploy-network

  # Add more containers below (nginx, postgres, etc.)

networks:
  dokploy-network:
    external: true # Indicates that this network is managed externally by Dokploy
