name: CheckoutTests

on:
  push:
    paths:
      - "apps/checkout/**"
      - ".github/workflows/checkoutTests.yaml"

jobs:
  tsc-and-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Install deps
        run: |
          npm install -g pnpm
          pnpm i

      - name: Run tsc
        run: |
          pnpm run check-types -- --scope="checkout"

      - name: Run lint
        run: |
          pnpm turbo run lint -- --scope="checkout"
