name: Checkout app checks

on:
  push:
    paths:
      - "apps/checkout-app/**"
      - ".github/workflows/checkout-app.yaml"

jobs:
  tsc-and-linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Install deps
        run: |
          npm install -g pnpm
          pnpm i

      - name: Run tsc
        run: |
          pnpm run check-types --scope="checkout-app"

      - name: Run lint
        run: |
          pnpm run lint --scope="checkout-app"

      - name: Run tests
        run: |
          pnpm run test --scope="checkout-app"
