name: QA
on: [pull_request]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.5.2 # version used by Vercel

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"

      # @todo: cache this on Vercel https://turborepo.org/docs/ci/github-actions
      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Validate paths
        env:
          SALEOR_API_URL: https://master.staging.saleor.cloud/graphql/
        run: |
          pnpm --filter=storefront paths
          pnpm prettier --write ./apps/storefront/lib/\$path.ts
          git diff --exit-code ./apps/storefront/lib/\$path.ts

      - name: Check linters
        run: pnpm run lint

      - name: Check TypeScript
        run: pnpm run check-types

      - name: Run tests
        env:
          TEST_MOLLIE_KEY: ${{ secrets.TEST_MOLLIE_KEY }}
          TEST_MOLLIE_PROFILE_ID: ${{ secrets.TEST_MOLLIE_PROFILE_ID }}
          SETTINGS_ENCRYPTION_SECRET: "testng"
        run: pnpm run test
